#!/usr/bin/env bash
#
# SteamVault Phase 0 PoC -- WP 0.6, Scenario A: hosts-file mode for the
# Linux-Steam-client (WSL2) test. Run this INSIDE WSL2 Ubuntu, after
# wsl-setup.sh has run at least once (see PROTOCOL.md section 4).
#
# What this does: adds a `lancache.steamcontent.com -> <host-ip>` line to
# WSL2's own /etc/hosts -- the exact mechanism WP 0.3 used on the Windows
# side, mirrored here for a fair comparison. Known upstream quirk
# (docs/PROJECT_PLAN.md section 7): the LINUX Steam client does not perform
# this hostname lookup at all, unlike the Windows client. So the CORRECT,
# expected result here is ZERO cache traffic -- this script cannot, by
# design, make the client succeed at something it doesn't attempt; it only
# sets up the precondition cleanly and verifies the DNS state is exactly as
# expected *before* you start Steam, so that a null result is trustworthy
# evidence rather than an artifact of a broken setup.
#
# Usage:
#   ./scenario-a.sh              set up (idempotent -- safe to re-run)
#   ./scenario-a.sh --rollback   remove the hosts-file line again

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/wsl-env"
HOSTS_FILE="/etc/hosts"
MARKER_BEGIN="# steamvault-scenario-a BEGIN (auto-generated by scenario-a.sh -- safe to delete this block, or run 'scenario-a.sh --rollback')"
MARKER_END="# steamvault-scenario-a END"

usage() {
    echo "Usage: $0 [--rollback]" >&2
    exit 1
}

MODE="setup"
if [[ $# -gt 0 ]]; then
    case "$1" in
        --rollback) MODE="rollback" ;;
        -h|--help)  usage ;;
        *) echo "Unknown argument: $1" >&2; usage ;;
    esac
fi

# Removes the marker block if present. Safe to call even if it isn't there.
remove_block() {
    if grep -qF "$MARKER_BEGIN" "$HOSTS_FILE" 2>/dev/null; then
        sudo sed -i "\#$(printf '%s' "$MARKER_BEGIN" | sed 's/[.[\*^$/#]/\\&/g')#,\#$(printf '%s' "$MARKER_END" | sed 's/[.[\*^$/#]/\\&/g')#d" "$HOSTS_FILE"
        return 0
    fi
    return 1
}

if [[ "$MODE" == "rollback" ]]; then
    if remove_block; then
        echo "Removed the scenario-a hosts-file block from $HOSTS_FILE."
    else
        echo "No scenario-a hosts-file block found in $HOSTS_FILE -- nothing to roll back."
    fi
    echo ""
    echo "Verify: getent hosts lancache.steamcontent.com"
    echo "  (should no longer resolve to your cache host IP)"
    exit 0
fi

if [[ ! -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE not found -- run ./wsl-setup.sh first." >&2
    exit 1
fi
# shellcheck disable=SC1090
source "$ENV_FILE"
: "${WSL_LINUX_TEST_HOST_IP:?WSL_LINUX_TEST_HOST_IP missing from wsl-env -- re-run ./wsl-setup.sh}"

# Idempotent: drop any previous block first, so re-running this after the
# host IP changed doesn't leave stale duplicate lines behind.
remove_block >/dev/null || true

sudo tee -a "$HOSTS_FILE" >/dev/null <<EOF
$MARKER_BEGIN
$WSL_LINUX_TEST_HOST_IP lancache.steamcontent.com
$MARKER_END
EOF

echo "Added hosts entry: $WSL_LINUX_TEST_HOST_IP lancache.steamcontent.com"
echo ""

# --- verify the DNS resolution state before handing over to Steam ----------
echo "Verifying resolution state..."
RESOLVED="$(getent hosts lancache.steamcontent.com 2>/dev/null | awk '{print $1; exit}' || true)"
if [[ "$RESOLVED" == "$WSL_LINUX_TEST_HOST_IP" ]]; then
    echo "[ OK ] lancache.steamcontent.com -> $RESOLVED (matches the expected host IP)"
else
    echo "[FAIL] lancache.steamcontent.com -> '${RESOLVED:-<no result>}', expected $WSL_LINUX_TEST_HOST_IP" >&2
    exit 1
fi

# Confirm dnsmasq is NOT active -- a running dnsmasq answering the wildcard
# would contaminate Scenario A's null-result evidence (that's Scenario B's
# job, not this one's).
DNSMASQ_ACTIVE=0
if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet dnsmasq 2>/dev/null; then
    DNSMASQ_ACTIVE=1
elif pgrep -x dnsmasq >/dev/null 2>&1; then
    DNSMASQ_ACTIVE=1
fi
if [[ "$DNSMASQ_ACTIVE" -eq 1 ]]; then
    echo "" >&2
    echo "[WARN] dnsmasq is currently ACTIVE. Scenario A expects it OFF (a wildcard" >&2
    echo "       DNS rewrite is Scenario B's mechanism, not this one's)." >&2
    echo "       Run: ./scenario-b.sh --rollback   to disable it, then re-run this script." >&2
fi

echo ""
echo "Scenario A is set up. Timestamp marker (note this down for"
echo "analyze-windows.ps1 -From):"
date -Is
echo ""
echo "Next (see PROTOCOL.md section 4.1):"
echo "  1. Fully quit Steam if it's already running, then relaunch it."
echo "  2. Install/download the test game (Spacewar, AppID 480, is recommended)."
echo "  3. Once done, run 'date -Is' again for the -To marker."
echo "  4. While/after downloading, cross-check from inside WSL:"
echo "       netstat -tnp 2>/dev/null | grep steam"
echo "     (expect NO established connection to $WSL_LINUX_TEST_HOST_IP)"
echo "  5. On the Windows side:"
echo "       poc\\linux-client-test\\analyze-windows.ps1 -Scenario A -From <start> -To <end>"
